config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post],
        as: 'auth' # used by omniauth

  match '/signin', to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :roles, param: :key
  resources :users, param: :username

  match '/', to: 'users#index', via: :all, as: 'root'
  match '/', to: redirect('/users'), via: :all
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  = link_to('User Manager', users_path, class: 'navbar-brand')
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item{class: ('active' if yield(:active_nav) == 'users')}
        = link_to('Users', users_path, class: 'nav-link nav-item')
      %li.nav-item{class: ('active' if yield(:active_nav) == 'roles')}
        = link_to('Roles', roles_path, class: 'nav-link nav-item')
    %ul.navbar-nav.my-2.my-lg-0
      %li.nav-item.dropdown
        %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          = fa_icon('user')
          = current_user
        .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
          = link_to('Sign Out', signout_path, method: :delete, class: 'dropdown-item')

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title User Manager
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

  %body
    = render 'layouts/header'

    .container-fluid
      = flashes
      = yield